# Generated by Django 3.0.5 on 2020-04-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('is_custom', models.BooleanField()),
                ('is_expense', models.BooleanField(choices=[(True, 'Expenses'), (False, 'Earnings')])),
                ('icon', models.CharField(
                    choices=[('salary.png', 'salary.png'), ('business.png', 'business.png'), ('gifts.png', 'gifts.pn'),
                             ('extra-income.png', 'extra-income.png'), ('loan.png', 'loan.png'),
                             ('parental-leave.png', 'parental-leave.png'), ('insurance.png', 'insurance.png'),
                             ('food.png', 'food.png'), ('shopping.png', 'shopping.png'),
                             ('transport.png', 'transport.png'), ('home.png', 'home.png'), ('bills.png', 'bills.png'),
                             ('groceries.png', 'groceries.png'), ('health.png', 'health.png'),
                             ('entertainment.png', 'entertainment.png')], max_length=500)),
            ],
        ),
    ]
