# Generated by Django 3.0.5 on 2020-04-23 07:58

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_currency', djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='PHP', editable=False, max_length=3)),
                ('balance', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PHP', max_digits=14)),
                ('progress', models.FloatField(verbose_name=builtins.max)),
                ('target_amount_currency', djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='PHP', editable=False, max_length=3)),
                ('target_amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PHP', max_digits=14)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='PHP', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PHP', max_digits=14)),
                ('date', models.DateField()),
                ('is_expense', models.BooleanField(choices=[(True, 'Expenses'), (False, 'Earnings')])),
                ('note', models.CharField(blank=True, max_length=3000, null=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goal.Goal')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
