# Generated by Django 3.0.5 on 2020-04-23 10:20

from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_auto_20200423_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PHP', max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0.0001)]),
        ),
    ]
