# Generated by Django 3.0.5 on 2020-04-23 18:58

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goal', '0005_auto_20200424_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goaltransaction',
            name='amount',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='PHP', max_digits=14,
                                                   validators=[djmoney.models.validators.MinMoneyValidator(1)]),
        ),
    ]
