# Generated by Django 3.0.5 on 2020-05-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0007_auto_20200510_1907'),
        ('goal', '0007_auto_20200510_1915'),
    ]

    operations = [
    ]
