# Generated by Django 3.0.5 on 2020-05-20 23:48

from django.db import migrations, models
import penny_pincher.validators


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0008_merge_20200511_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='opened',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='goaltransaction',
            name='date',
            field=models.DateField(validators=[penny_pincher.validators.NotInFutureValidator]),
        ),
    ]
