# Generated by Django 3.0.5 on 2020-05-21 00:17

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0009_auto_20200521_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='XYZ', editable=False, max_length=3),
        ),
    ]
