# Generated by Django 3.0.5 on 2020-04-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='note',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
