# Generated by Django 3.0.5 on 2020-04-16 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20200416_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_Expense',
            new_name='is_expense',
        ),
    ]
