# Generated by Django 3.0.5 on 2020-04-17 04:26

from django.conf import settings
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0004_auto_20200416_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='PHP', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('PHP', 'Philippine Peso')], default='PHP', editable=False, max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('name', 'type', 'owner')},
        ),
    ]
