# Generated by Django 3.0.5 on 2020-04-17 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_auto_20200417_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='isExpense',
            new_name='is_expense',
        ),
    ]
