# Generated by Django 3.0.5 on 2020-04-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20200417_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.Category'),
        ),
    ]
