# Generated by Django 3.0.5 on 2020-05-11 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_auto_20200510_1915'),
        ('wallet', '0006_auto_20200510_1907'),
    ]

    operations = [
    ]
