# Generated by Django 3.0.5 on 2020-04-17 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('wallet', '0007_auto_20200417_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='category.Category'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
