# Generated by Django 3.0.5 on 2020-04-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20200417_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='is_expense',
            field=models.BooleanField(choices=[(True, 'Expenses'), (False, 'Earnings')]),
        ),
    ]
